<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pSMLearningEcosystems" nsURI="https://raw.githubusercontent.com/aliciagh/ecometamodel/master/PSMLearningEcosystems/model/pSMLearningEcosystems.ecore"
    nsPrefix="psmLearningEcosystems">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareTool" abstract="true" eSuperTypes="#//Component">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="differentService differentConfig ownContainer"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="differentService" value="&#xA;&#x9;&#x9;&#x9;self.consumedService -> forAll(k | k.providerAPI -> forAll(j | j &lt;> self))"/>
      <details key="differentConfig" value="&#xA;&#x9;&#x9;&#x9;self.usedFile -> forAll(k | k.fileProvider &lt;> self)"/>
      <details key="ownContainer" value="&#xA;&#x9;&#x9;&#x9;self.softwareComponent -> forAll(k | k &lt;> self)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="softwareContainer" eType="#//SoftwareTool"
        eOpposite="#//SoftwareTool/softwareComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedAPI" ordered="false"
        upperBound="-1" eType="#//RESTfulAPI" eOpposite="#//RESTfulAPI/providerAPI"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="consumedService" ordered="false"
        upperBound="-1" eType="#//RESTfulAPI" eOpposite="#//RESTfulAPI/RESTClient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="file" ordered="false" upperBound="-1"
        eType="#//File" eOpposite="#//File/fileProvider"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedFile" ordered="false"
        upperBound="-1" eType="#//File" eOpposite="#//File/fileConsumer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="softwareComponent" ordered="false"
        upperBound="-1" eType="#//SoftwareTool" eOpposite="#//SoftwareTool/softwareContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RESTfulAPI" eSuperTypes="#//CommunicationSolution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//RESTService" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providerAPI" upperBound="-1"
        eType="#//SoftwareTool" eOpposite="#//SoftwareTool/supportedAPI"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RESTClient" ordered="false"
        upperBound="-1" eType="#//SoftwareTool" eOpposite="#//SoftwareTool/consumedService"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RESTService">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="endpointUnique"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="endpointUnique" value="&#xA;&#x9;&#x9;&#x9;RESTService.allInstances() -> forAll (p1,p2 |  p1 &lt;> p2 implies p1.endPoint &lt;> p2.endPoint)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endPoint" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" lowerBound="1"
        eType="#//RESTInterface" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="File" eSuperTypes="#//CommunicationSolution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fileProvider" lowerBound="1"
        eType="#//SoftwareTool" eOpposite="#//SoftwareTool/file"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fileConsumer" ordered="false"
        upperBound="-1" eType="#//SoftwareTool" eOpposite="#//SoftwareTool/usedFile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodologyDocument" eSuperTypes="#//Document">
    <eStructuralFeatures xsi:type="ecore:EReference" name="people" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//People" eOpposite="#//People/establishedMethodology"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tool" abstract="true" eSuperTypes="#//SoftwareTool"/>
  <eClassifiers xsi:type="ecore:EClass" name="DSpace" instanceClassName="s" eSuperTypes="#//SoftwareTool"/>
  <eClassifiers xsi:type="ecore:EClass" name="People" abstract="true" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="establishedMethodology"
        ordered="false" upperBound="-1" eType="#//MethodologyDocument" eOpposite="#//MethodologyDocument/people"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="performedManagement" ordered="false"
        upperBound="-1" eType="#//ManagementPlan" eOpposite="#//ManagementPlan/people"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CASoverLDAP" eSuperTypes="#//Infrastructure"/>
  <eClassifiers xsi:type="ecore:EClass" name="Facebook" eSuperTypes="#//Tool">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="link" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identificator" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secretKey" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RESTInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//RESTOperation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hakara" eSuperTypes="#//Infrastructure"/>
  <eClassifiers xsi:type="ecore:EClass" name="Manager" eSuperTypes="#//People"/>
  <eClassifiers xsi:type="ecore:EClass" name="Infrastructure" abstract="true" eSuperTypes="#//SoftwareTool"/>
  <eClassifiers xsi:type="ecore:EClass" name="ManagementPlan" eSuperTypes="#//Document">
    <eStructuralFeatures xsi:type="ecore:EReference" name="people" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//People" eOpposite="#//People/performedManagement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectives" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodology" upperBound="-1"
        eType="#//MethodologyDocument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApacheSolr" eSuperTypes="#//Infrastructure"/>
  <eClassifiers xsi:type="ecore:EClass" name="Prometheus" eSuperTypes="#//Infrastructure"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ecosystem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="communication" upperBound="-1"
        eType="#//CommunicationSolution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RESTOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNotification" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isListener" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Drupal" eSuperTypes="#//Tool"/>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationSolution" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ITManager" eSuperTypes="#//People"/>
  <eClassifiers xsi:type="ecore:EClass" name="Document" abstract="true" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="WordPress" eSuperTypes="#//Tool"/>
  <eClassifiers xsi:type="ecore:EClass" name="Twitter" eSuperTypes="#//Tool">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="link" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="apiKey" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="apiSecret" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="token" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokenSecret" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Moodle" eSuperTypes="#//Tool"/>
  <eClassifiers xsi:type="ecore:EClass" name="LImeSurvey" eSuperTypes="#//Tool"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency" eSuperTypes="#//Document">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceTool" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destinationTool" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="automatic" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plugin" eSuperTypes="#//Tool">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="pluginNotContentOthers"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="pluginNotContentOthers" value="&#xA;&#x9;&#x9;&#x9;self.softwareComponent -> isEmpty() and &#xA;&#x9;&#x9;&#x9;self.softwareContainer -> notEmpty()"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
